# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 20) do

  create_table "competition_states", :force => true do |t|
    t.column "name", :string, :limit => 32, :default => "", :null => false
  end

  create_table "competitions", :force => true do |t|
    t.column "name",                 :string,   :limit => 32, :default => "", :null => false
    t.column "description",          :text
    t.column "deadline_on",          :datetime
    t.column "updated_on",           :datetime
    t.column "created_on",           :datetime
    t.column "competition_state_id", :integer
  end

  create_table "entries", :force => true do |t|
    t.column "name",           :string,   :limit => 256, :default => ""
    t.column "description",    :text
    t.column "filename",       :string,   :limit => 256
    t.column "thumbnail",      :string,   :limit => 256
    t.column "updated_on",     :datetime
    t.column "created_on",     :datetime
    t.column "entry_state_id", :integer
    t.column "user_id",        :integer
    t.column "competition_id", :integer
  end

  create_table "entry_states", :force => true do |t|
    t.column "name", :string, :limit => 32, :default => "", :null => false
  end

  create_table "infos", :force => true do |t|
    t.column "infotext", :text, :default => "", :null => false
  end

  create_table "news", :force => true do |t|
    t.column "user_id",    :integer
    t.column "title",      :string
    t.column "news_text",  :text
    t.column "created_at", :datetime
  end

  create_table "news_comments", :force => true do |t|
    t.column "user_id",      :integer
    t.column "created_at",   :datetime
    t.column "news_id",      :integer
    t.column "comment_text", :text
  end

  create_table "roles", :force => true do |t|
    t.column "name", :string, :limit => 32, :default => "", :null => false
  end

  create_table "roles_users", :id => false, :force => true do |t|
    t.column "user_id", :integer, :null => false
    t.column "role_id", :integer, :null => false
  end

  create_table "rules", :force => true do |t|
    t.column "ruletext", :text
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "users", :force => true do |t|
    t.column "login",         :string,   :limit => 256, :default => "", :null => false
    t.column "password_hash", :string,   :limit => 64
    t.column "ticketno",      :string,   :limit => 32,  :default => "", :null => false
    t.column "name",          :string,   :limit => 64
    t.column "email",         :string,   :limit => 32
    t.column "description",   :text
    t.column "updated_on",    :datetime
    t.column "created_on",    :datetime
    t.column "phoneno",       :string
    t.column "address",       :string
    t.column "seat",          :string
    t.column "status",        :string
    t.column "company",       :string
    t.column "team",          :string
    t.column "cc_nick",       :string
  end

  create_table "votes", :force => true do |t|
    t.column "rating",     :integer
    t.column "created_on", :datetime
    t.column "entry_id",   :integer
    t.column "user_id",    :integer
  end

end
